coverage:
  status:
    project:
      default:
        threshold: 20%

    patch:
      target: 80%                 # 可选：期望值，低于它会标黄
      threshold: 5%               # 可选：允许比目标低 5%
      informational: true         # 👈 关键：只做提示，不报错！
component_management:
  individual_components:
    - component_id: "springboot2"
      paths:
        - "dify/dify-client/dify-client-spring5/"
        - "dify/spring-boot2-starter/"
    - component_id: "springboot3"
      paths:
        - "dify/dify-client/dify-client-spring6/"
        - "dify/spring-boot-starter/"

comment:
  layout: "header, diff, flags, components"  # show component info in the PR comment

